name: Node.js CI

on:
  pull_request

env:
  PORT: ${{ secrets.PORT }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_PATH: ${{ secrets.MONGO_PATH }}

  MONGO_TEST_USER: ${{ secrets.MONGO_TEST_USER }}
  MONGO_TEST_PASSWORD: ${{ secrets.MONGO_TEST_PASSWORD }}
  MONGO_TEST_PATH: ${{ secrets.MONGO_TEST_PATH }}

  JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
  REFRESH_TOKEN_EXPIRATION_TIME: ${{ secrets.REFRESH_TOKEN_EXPIRATION_TIME }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

  RATE_LIMIT_TIMESPAN: ${{ secrets.RATE_LIMIT_TIMESPAN }}
  RATE_LIMIT: ${{ secrets.RATE_LIMIT }}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test -- --coverage --coverageReporters="cobertura"

      - name: Code Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: file
          thresholds: '70 90'

      - name: Add Coverage To PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md